paths:
  data: data
  static: public
  uploads: public/images
collections_config:
  data:
    path: data
    disable_add: true
    disable_add_folder: true
  posts:
    path: src/content/blog
    parser: front-matter
    output: true
    url: '/blog/[slug]/'
    _enabled_editors:
      - content
      - visual
    add_options:
      - name: Add New Post
        schema: default
        icon: post_add
    schemas:
      default:
        name: New Post
        path: schemas/post.mdx
    _inputs:
      title:
        empty_type: string
      image:
        empty_type: string
      image_alt:
        empty_type: string
      author:
        empty_type: string
      tags:
        type: multiselect
        allow_create: true
        empty_type: array
  pages:
    path: src/content/pages
    url: '/[slug]/'
    output: true
    icon: wysiwyg
    _enabled_editors:
      - visual
    filter:
      base: strict
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Blogging
    collections:
      - posts
  - heading: Data
    collections:
      - data
_inputs:
  layout:
    hidden: true
  date:
    instance_value: now
  title_suffix:
    comment: Added at the end of the title and highlighted in a different color
  page_size:
    type: number
    comment: The number of collection items to list per page
  social:
    options:
      preview:
        icon: link
  links:
    options:
      preview:
        icon: link
  items:
    options:
      preview:
        icon: link
  social[*].icon:
    type: select
    options:
      values:
        - ph-facebook-logo
        - ph-instagram-logo
        - ph-twitter-logo
        - ph-github-logo
        - ph-youtube-logo
  logo_url:
    comment: Link for the logo in the top left of the footer
  copyright:
    comment: Automatically prefixed with the current year
  isActive:
    type: switch
  page_description:
    comment: Defaults to the description set in the Site SEO data file
  favicon_icon:
    type: image
    comment: For the shortcut icon meta tag
  faivcon_image:
    type: image
    comment: For the icon meta tag
  canonical_url:
    comment: Defaults to the pages url
  featured_image:
    comment: Defaults to the image set in the Site SEO data file
  open_graph_type:
    comment: Defaults to the type 'website'
  author_twitter_handle:
    comment: Defaults to the twitter site value set in the Site SEO data file
  no_index:
    type: checkbox
    comment:
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag

data_config:
  icons:
    path: data/icons.json

_snippets_imports:
  mdx: true
_snippets:
  alert:
    template: mdx_component
    inline: false
    preview:
      text:
        - key: alert_message
        - 'Alert'
    definitions:
      component_name: Alert
      named_args:
        - editor_key: background_color
          source_key: background_color
          type: string
        - editor_key: alert_message
          source_key: alert_message
          type: string
    _inputs:
      background_color:
        type: color
      alert_message:
        comment: This is the text for the alert
  video:
    template: mdx_component
    inline: false
    preview:
      text: Video
    definitions:
      component_name: Video
      named_args:
        - editor_key: src
          source_key: src
          type: string
    _inputs:
      src:
        type: file
        options:
          paths:
            uploads: public/videos
  file:
    template: mdx_component
    inline: false
    preview:
      text: File
    definitions:
      component_name: File
      named_args:
        - editor_key: src
          source_key: src
          type: string
        - editor_key: file_name
          source_key: file_name
          type: string
        - editor_key: link_message
          source_key: link_message
          type: string
    _inputs:
      src:
        type: file
        label: File source
        options:
          paths:
            uploads: public/documents
      file_name:
        type: string
        comment: The name of the file, once downloaded.
      link_message:
        type: string
        comment: The text for the download link
  mdx_tint:
    template: mdx_paired_component
    inline: true
    preview:
      text: Tint
    definitions:
      component_name: Tint
      content_key: inner_text
      named_args:
        - editor_key: color
          source_key: tint_color
          type: string
    _inputs:
      tint_color:
        type: color
      inner_text:
        comment: This text will be tinted
