# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Text & animated border image. Buttons with icons.
  icon: 'cottage'
  tags:
    - Image
    - Animation
    - Text
    - Buttons

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    heading_text: Astro Bookshop Starter
    heading_gradient_color: '#a0a2ff'
  subheading:
    text: >-
      A starting point for those looking to build a website with Astro, using Bookshop components in CloudCannon. Create your own copy, and start creating your own components to use in the CloudCannon CMS.
    color: '#393939'
  image:
    image_path: /src/assets/images/featured-image-5.jpg
    altText: An image
    name: The hero with Astro Image
    width: 600
    height: 600
  buttons:
    - text: CloudCannon
      icon: Envelope
      link: 'https://www.cloudcannon.com'
      border_only: false
      background_color: '#034ad8'
      hover_brightness: 0.85
      text_color: '#ffffff'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  width:
    type: number
  height:
    type: number
  icon:
    type: select
    options:
      values: data.icons
  image_path:
    type: image
    options:
      paths:
        uploads: src/assets
