# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Text & animated border image. Buttons with icons.
  icon: 'cottage'
  tags:
    - Image
    - Animation
    - Text
    - Buttons

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: '#ffffff'
  heading:
    heading_text: Astro Bookshop Starter
    heading_gradient_color: '#a0a2ff'
  subheading:
    text: >-
      A starting point for those looking to build a website with Astro, using Bookshop components in CloudCannon. Create your own copy, and start creating your own components to use in the CloudCannon CMS.
    color: '#393939'
  image:
    image_path: /src/assets/images/featured-image-5.jpg
    alt_text: An image
  buttons:
    - text: CloudCannon
      icon: Envelope
      link: 'https://www.cloudcannon.com'
      border_only: false
      background_color: '#034ad8'
      hover_brightness: 0.85
      text_color: '#ffffff'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  width:
    type: number
  height:
    type: number
  icon:
    type: select
    options:
      values: data.icons
  image_path:
    type: image
    options:
      paths:
        uploads: src/assets
  heading_gradient_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  text:
    type: markdown
    options:
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      link: true
      bulletedlist: true
      numberedlist: true
      embed: true
      horizontalrule: true
      image: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
